name: hello workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print INSTA ID
      run: echo "https://www.instagram.com/${pull_request}/"
