name: Auto Merge Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge pull request
        uses: repo-sync/github-sync@v2
        with:
          source_branch: ${{ github.head_ref }}
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
